<?php

namespace Database\Seeders;

use App\Models\MenuCategory;
use App\Models\MenuItem;
use Illuminate\Database\Seeder;

class MenuItemSeeder extends Seeder
{
    public function run(): void
    {
        // Получаем категории по slug для удобства
        $cats = MenuCategory::pluck('id', 'slug');

        $items = [

            // ── Завтраки ──────────────────────────────────────────────────
            [
                'menu_category_id' => $cats['breakfast'],
                'title_ru'         => 'Классический завтрак',
                'title_en'         => 'Classic Breakfast',
                'description_ru'   => 'Яйца пашот на тосте бриошь, бекон из фермерской свинины, запечённые томаты черри, грибы шиитаке, свежевыжатый сок',
                'description_en'   => 'Poached eggs on brioche toast, farm bacon, baked cherry tomatoes, shiitake mushrooms, freshly squeezed juice',
                'price'            => 890,
                'featured'         => true,
                'sort_order'       => 1,
            ],
            [
                'menu_category_id' => $cats['breakfast'],
                'title_ru'         => 'Омлет с трюфелем и пармезаном',
                'title_en'         => 'Truffle and Parmesan Omelette',
                'description_ru'   => 'Нежный омлет из трёх яиц с тёртым трюфелем, выдержанным пармезаном и свежей зеленью. Подаётся с тостами на закваске',
                'description_en'   => 'Tender three-egg omelette with grated truffle, aged parmesan and fresh herbs. Served with sourdough toast',
                'price'            => 1250,
                'featured'         => false,
                'sort_order'       => 2,
            ],
            [
                'menu_category_id' => $cats['breakfast'],
                'title_ru'         => 'Французские тосты с ягодами',
                'title_en'         => 'French Toast with Berries',
                'description_ru'   => 'Тосты из бриоши в яично-сливочном кляре, свежие сезонные ягоды, кленовый сироп, взбитые сливки',
                'description_en'   => 'Brioche toast in egg-cream batter, fresh seasonal berries, maple syrup, whipped cream',
                'price'            => 750,
                'featured'         => false,
                'sort_order'       => 3,
            ],
            [
                'menu_category_id' => $cats['breakfast'],
                'title_ru'         => 'Круассан с лососем и икрой',
                'title_en'         => 'Croissant with Salmon and Caviar',
                'description_ru'   => 'Масляный круассан собственной выпечки, слабосолёный лосось, сливочный сыр, красная икра, каперсы, лимон',
                'description_en'   => 'Buttery house-baked croissant, lightly salted salmon, cream cheese, red caviar, capers, lemon',
                'price'            => 1450,
                'featured'         => true,
                'sort_order'       => 4,
            ],
            [
                'menu_category_id' => $cats['breakfast'],
                'title_ru'         => 'Каша из полбы с лесными ягодами',
                'title_en'         => 'Spelt Porridge with Forest Berries',
                'description_ru'   => 'Томлёная каша из полбы на топлёном молоке, свежие лесные ягоды, мёд алтайской пасеки, грецкий орех',
                'description_en'   => 'Slow-cooked spelt porridge in clarified milk, fresh forest berries, Altai honey, walnuts',
                'price'            => 590,
                'featured'         => false,
                'sort_order'       => 5,
            ],

            // ── Холодные закуски ──────────────────────────────────────────
            [
                'menu_category_id' => $cats['cold'],
                'title_ru'         => 'Тартар из говядины',
                'title_en'         => 'Beef Tartare',
                'description_ru'   => 'Рубленая мраморная говядина, трюфельное масло, каперсы, дижонская горчица, перепелиный желток, тосты',
                'description_en'   => 'Chopped marbled beef, truffle oil, capers, Dijon mustard, quail egg yolk, toast',
                'price'            => 1650,
                'featured'         => true,
                'sort_order'       => 1,
            ],
            [
                'menu_category_id' => $cats['cold'],
                'title_ru'         => 'Карпаччо из гребешка',
                'title_en'         => 'Scallop Carpaccio',
                'description_ru'   => 'Тонко нарезанный дальневосточный гребешок, лимонное масло, икра тобико, микрозелень, пармезан',
                'description_en'   => 'Thinly sliced Far Eastern scallop, lemon oil, tobiko caviar, microgreens, parmesan',
                'price'            => 1890,
                'featured'         => false,
                'sort_order'       => 2,
            ],
            [
                'menu_category_id' => $cats['cold'],
                'title_ru'         => 'Фуа-гра с бриошью',
                'title_en'         => 'Foie Gras with Brioche',
                'description_ru'   => 'Террин из гусиной фуа-гра, желе из Сотерна, бриошь, конфитюр из инжира',
                'description_en'   => 'Goose foie gras terrine, Sauternes jelly, brioche, fig jam',
                'price'            => 2200,
                'featured'         => true,
                'sort_order'       => 3,
            ],
            [
                'menu_category_id' => $cats['cold'],
                'title_ru'         => 'Сельдь под шубой по-нашему',
                'title_en'         => 'Our-Style Herring Under a Fur Coat',
                'description_ru'   => 'Авторская интерпретация классики: слабосолёная сельдь, запечённая свёкла, картофель конфи, перепелиное яйцо, укроп',
                'description_en'   => 'An author\'s interpretation of the classic: lightly salted herring, baked beets, potato confit, quail egg, dill',
                'price'            => 780,
                'featured'         => false,
                'sort_order'       => 4,
            ],

            // ── Салаты ────────────────────────────────────────────────────
            [
                'menu_category_id' => $cats['salads'],
                'title_ru'         => 'Салат с лангустинами',
                'title_en'         => 'Langoustine Salad',
                'description_ru'   => 'Жареные лангустины, авокадо, манго, руккола, помело, соус из маракуйи',
                'description_en'   => 'Pan-fried langoustines, avocado, mango, arugula, pomelo, passion fruit sauce',
                'price'            => 2100,
                'featured'         => true,
                'sort_order'       => 1,
            ],
            [
                'menu_category_id' => $cats['salads'],
                'title_ru'         => 'Цезарь с куриным су-вид',
                'title_en'         => 'Caesar with Sous-Vide Chicken',
                'description_ru'   => 'Куриное филе су-вид, салат романо, хрустящие гренки, пармезан, анчоусный соус цезарь',
                'description_en'   => 'Sous-vide chicken fillet, romaine lettuce, croutons, parmesan, anchovy caesar dressing',
                'price'            => 950,
                'featured'         => false,
                'sort_order'       => 2,
            ],
            [
                'menu_category_id' => $cats['salads'],
                'title_ru'         => 'Нисуаз с тунцом',
                'title_en'         => 'Tuna Niçoise',
                'description_ru'   => 'Жареный тунец, яйцо пашот, стручковая фасоль, томаты, маслины, картофель, анчоусная заправка',
                'description_en'   => 'Pan-seared tuna, poached egg, green beans, tomatoes, olives, potatoes, anchovy dressing',
                'price'            => 1350,
                'featured'         => false,
                'sort_order'       => 3,
            ],
            [
                'menu_category_id' => $cats['salads'],
                'title_ru'         => 'Тёплый салат с уткой конфи',
                'title_en'         => 'Warm Duck Confit Salad',
                'description_ru'   => 'Утиное конфи, микс листьев, груша, грецкий орех, горгонзола, апельсиновая заправка',
                'description_en'   => 'Duck confit, mixed leaves, pear, walnut, gorgonzola, orange dressing',
                'price'            => 1480,
                'featured'         => false,
                'sort_order'       => 4,
            ],

            // ── Супы ──────────────────────────────────────────────────────
            [
                'menu_category_id' => $cats['soups'],
                'title_ru'         => 'Французский луковый суп',
                'title_en'         => 'French Onion Soup',
                'description_ru'   => 'Карамелизированный лук, говяжий бульон, гренок с расплавленным грюйером',
                'description_en'   => 'Caramelized onion, beef broth, crouton with melted Gruyère',
                'price'            => 690,
                'featured'         => true,
                'sort_order'       => 1,
            ],
            [
                'menu_category_id' => $cats['soups'],
                'title_ru'         => 'Крем-суп из белых грибов',
                'title_en'         => 'Porcini Cream Soup',
                'description_ru'   => 'Белые грибы из Карелии, сливки, трюфельное масло, чипсы из пармезана',
                'description_en'   => 'Karelian porcini mushrooms, cream, truffle oil, parmesan crisps',
                'price'            => 780,
                'featured'         => false,
                'sort_order'       => 2,
            ],
            [
                'menu_category_id' => $cats['soups'],
                'title_ru'         => 'Уха по-царски',
                'title_en'         => 'Royal Fish Soup',
                'description_ru'   => 'Янтарный бульон из стерляди, семга, судак, осётр, икра, расстегай',
                'description_en'   => 'Amber sterlet broth, salmon, pike-perch, sturgeon, caviar, pirozhok',
                'price'            => 1200,
                'featured'         => true,
                'sort_order'       => 3,
            ],
            [
                'menu_category_id' => $cats['soups'],
                'title_ru'         => 'Бульон с равиоли из рикотты',
                'title_en'         => 'Broth with Ricotta Ravioli',
                'description_ru'   => 'Прозрачный куриный консоме, равиоли с рикоттой и шпинатом, трюфельная стружка',
                'description_en'   => 'Clear chicken consommé, ricotta and spinach ravioli, truffle shavings',
                'price'            => 720,
                'featured'         => false,
                'sort_order'       => 4,
            ],

            // ── Горячие блюда ─────────────────────────────────────────────
            [
                'menu_category_id' => $cats['hot'],
                'title_ru'         => 'Утиная грудка с вишнёвым соусом',
                'title_en'         => 'Duck Breast with Cherry Sauce',
                'description_ru'   => 'Утиная грудка средней прожарки, соус из тёмной вишни и портвейна, пюре из пастернака, хрустящий картофель',
                'description_en'   => 'Medium-cooked duck breast, dark cherry and port wine sauce, parsnip purée, crispy potatoes',
                'price'            => 2450,
                'featured'         => true,
                'sort_order'       => 1,
            ],
            [
                'menu_category_id' => $cats['hot'],
                'title_ru'         => 'Судак в кляре с икорным соусом',
                'title_en'         => 'Pike-Perch in Batter with Caviar Sauce',
                'description_ru'   => 'Филе волжского судака в хрустящем кляре, соус из сметаны и осетровой икры, картофельное пюре с укропом',
                'description_en'   => 'Volga pike-perch fillet in crispy batter, sour cream and sturgeon caviar sauce, mashed potatoes with dill',
                'price'            => 1980,
                'featured'         => false,
                'sort_order'       => 2,
            ],
            [
                'menu_category_id' => $cats['hot'],
                'title_ru'         => 'Телятина оссобуко',
                'title_en'         => 'Veal Osso Buco',
                'description_ru'   => 'Томлёная рулька телёнка по-милански, гремолата, шафрановое ризотто',
                'description_en'   => 'Braised veal shank Milanese-style, gremolata, saffron risotto',
                'price'            => 2890,
                'featured'         => false,
                'sort_order'       => 3,
            ],
            [
                'menu_category_id' => $cats['hot'],
                'title_ru'         => 'Лосось конфи с соусом из шампанского',
                'title_en'         => 'Salmon Confit with Champagne Sauce',
                'description_ru'   => 'Мурманский лосось медленного приготовления, соус из шампанского с икрой, спаржа, картофель дофинуа',
                'description_en'   => 'Slow-cooked Murmansk salmon, champagne caviar sauce, asparagus, potato dauphinoise',
                'price'            => 2650,
                'featured'         => true,
                'sort_order'       => 4,
            ],
            [
                'menu_category_id' => $cats['hot'],
                'title_ru'         => 'Каре ягнёнка с прованскими травами',
                'title_en'         => 'Rack of Lamb with Provençal Herbs',
                'description_ru'   => 'Каре ягнёнка в ароматной корочке из прованских трав, соус из красного вина, рататуй, розмариновый картофель',
                'description_en'   => 'Rack of lamb in an aromatic Provençal herb crust, red wine sauce, ratatouille, rosemary potatoes',
                'price'            => 3200,
                'featured'         => false,
                'sort_order'       => 5,
            ],

            // ── Гриль ─────────────────────────────────────────────────────
            [
                'menu_category_id' => $cats['grill'],
                'title_ru'         => 'Стейк рибай из мраморной говядины',
                'title_en'         => 'Ribeye Steak from Marbled Beef',
                'description_ru'   => 'Рибай зернового откорма Воронежской области, 350 г, соус беарнез, картофель фри, запечённые томаты',
                'description_en'   => 'Grain-fed ribeye from the Voronezh region, 350g, béarnaise sauce, french fries, baked tomatoes',
                'price'            => 3800,
                'featured'         => true,
                'sort_order'       => 1,
            ],
            [
                'menu_category_id' => $cats['grill'],
                'title_ru'         => 'Стейк филе-миньон',
                'title_en'         => 'Filet Mignon Steak',
                'description_ru'   => 'Вырезка высшего сорта, 200 г, соус из красного вина с трюфелем, сезонные овощи на гриле',
                'description_en'   => 'Premium tenderloin, 200g, red wine truffle sauce, seasonal grilled vegetables',
                'price'            => 4200,
                'featured'         => true,
                'sort_order'       => 2,
            ],
            [
                'menu_category_id' => $cats['grill'],
                'title_ru'         => 'Осётр на гриле',
                'title_en'         => 'Grilled Sturgeon',
                'description_ru'   => 'Стейк осётра астраханского, лимонное масло с каперсами, молодой картофель, спаржа',
                'description_en'   => 'Astrakhan sturgeon steak, lemon caper butter, new potatoes, asparagus',
                'price'            => 3100,
                'featured'         => false,
                'sort_order'       => 3,
            ],

            // ── Паста и ризотто ───────────────────────────────────────────
            [
                'menu_category_id' => $cats['pasta'],
                'title_ru'         => 'Ризотто с белым трюфелем',
                'title_en'         => 'White Truffle Risotto',
                'description_ru'   => 'Рис карнароли, бульон из пармезановых корок, масло из белого трюфеля, стружка трюфеля',
                'description_en'   => 'Carnaroli rice, parmesan rind broth, white truffle butter, truffle shavings',
                'price'            => 2100,
                'featured'         => true,
                'sort_order'       => 1,
            ],
            [
                'menu_category_id' => $cats['pasta'],
                'title_ru'         => 'Паппарделле с рагу из кролика',
                'title_en'         => 'Pappardelle with Rabbit Ragù',
                'description_ru'   => 'Домашняя паста паппарделле, рагу из фермерского кролика с оливками и тимьяном, пекорино',
                'description_en'   => 'Homemade pappardelle, farm rabbit ragù with olives and thyme, pecorino',
                'price'            => 1650,
                'featured'         => false,
                'sort_order'       => 2,
            ],
            [
                'menu_category_id' => $cats['pasta'],
                'title_ru'         => 'Тальятелле с лангустинами',
                'title_en'         => 'Tagliatelle with Langoustines',
                'description_ru'   => 'Домашняя паста тальятелле, лангустины из Баренцева моря, томаты черри, чеснок, базилик',
                'description_en'   => 'Homemade tagliatelle, Barents Sea langoustines, cherry tomatoes, garlic, basil',
                'price'            => 2300,
                'featured'         => false,
                'sort_order'       => 3,
            ],

            // ── Десерты ───────────────────────────────────────────────────
            [
                'menu_category_id' => $cats['desserts'],
                'title_ru'         => 'Крем-брюле с лавандой',
                'title_en'         => 'Lavender Crème Brûlée',
                'description_ru'   => 'Нежный заварной крем с прованской лавандой, хрустящая карамельная корочка, свежие ягоды',
                'description_en'   => 'Tender custard with Provençal lavender, crispy caramel crust, fresh berries',
                'price'            => 590,
                'featured'         => true,
                'sort_order'       => 1,
            ],
            [
                'menu_category_id' => $cats['desserts'],
                'title_ru'         => 'Шоколадный фондан с мороженым из базилика',
                'title_en'         => 'Chocolate Fondant with Basil Ice Cream',
                'description_ru'   => 'Шоколадный фондан из 72% бельгийского шоколада, жидкая начинка, мороженое из свежего базилика',
                'description_en'   => 'Chocolate fondant from 72% Belgian chocolate, liquid center, fresh basil ice cream',
                'price'            => 690,
                'featured'         => true,
                'sort_order'       => 2,
            ],
            [
                'menu_category_id' => $cats['desserts'],
                'title_ru'         => 'Тарт татен с кальвадосом',
                'title_en'         => 'Tarte Tatin with Calvados',
                'description_ru'   => 'Перевёрнутый яблочный тарт с нормандским кальвадосом, мороженое из солёной карамели',
                'description_en'   => 'Upside-down apple tart with Norman Calvados, salted caramel ice cream',
                'price'            => 650,
                'featured'         => false,
                'sort_order'       => 3,
            ],
            [
                'menu_category_id' => $cats['desserts'],
                'title_ru'         => 'Птифуры и трюфели ручной работы',
                'title_en'         => 'Petits Fours and Handmade Truffles',
                'description_ru'   => 'Ассорти из шести миниатюрных пирожных и шести шоколадных трюфелей, к кофе или чаю',
                'description_en'   => 'Assortment of six miniature pastries and six chocolate truffles, served with coffee or tea',
                'price'            => 780,
                'featured'         => false,
                'sort_order'       => 4,
            ],
            [
                'menu_category_id' => $cats['desserts'],
                'title_ru'         => 'Медовик с манго и маракуйей',
                'title_en'         => 'Honey Cake with Mango and Passion Fruit',
                'description_ru'   => 'Авторская интерпретация классического медовика: тончайшие коржи, крем с манго и маракуйей, мороженое из сметаны',
                'description_en'   => 'An author\'s interpretation of the classic honey cake: thin layers, mango-passion fruit cream, sour cream ice cream',
                'price'            => 620,
                'featured'         => true,
                'sort_order'       => 5,
            ],

            // ── Винная карта ──────────────────────────────────────────────
            [
                'menu_category_id' => $cats['wine'],
                'title_ru'         => 'Château Margaux 2018',
                'title_en'         => 'Château Margaux 2018',
                'description_ru'   => 'Франция, Бордо, AOC Margaux. Красное сухое. Бархатные танины, ноты чёрной смородины, сигарного ящика и фиалки. Выдержка 18 месяцев в новых дубовых бочках',
                'description_en'   => 'France, Bordeaux, AOC Margaux. Dry red. Velvety tannins, notes of blackcurrant, cigar box and violet. Aged 18 months in new oak barrels',
                'price'            => 48000,
                'featured'         => true,
                'sort_order'       => 1,
            ],
            [
                'menu_category_id' => $cats['wine'],
                'title_ru'         => 'Dom Pérignon Vintage 2013',
                'title_en'         => 'Dom Pérignon Vintage 2013',
                'description_ru'   => 'Франция, Шампань. Игристое белое. Утончённые пузырьки, ноты белого персика, миндаля и бриоши. Идеально к морепродуктам',
                'description_en'   => 'France, Champagne. Sparkling white. Refined bubbles, notes of white peach, almond and brioche. Perfect with seafood',
                'price'            => 35000,
                'featured'         => true,
                'sort_order'       => 2,
            ],
            [
                'menu_category_id' => $cats['wine'],
                'title_ru'         => 'Пино Нуар «Фанагория» 2021',
                'title_en'         => 'Pinot Noir "Fanagoria" 2021',
                'description_ru'   => 'Россия, Краснодарский край. Красное сухое. Лучший российский пино нуар: вишня, малина, лёгкие дымные нотки. Гран-при Decanter 2022',
                'description_en'   => 'Russia, Krasnodar region. Dry red. The best Russian Pinot Noir: cherry, raspberry, light smoky notes. Decanter Grand Prix 2022',
                'price'            => 4800,
                'featured'         => false,
                'sort_order'       => 3,
            ],
            [
                'menu_category_id' => $cats['wine'],
                'title_ru'         => 'Рислинг «Абрау-Дюрсо» 2022',
                'title_en'         => 'Riesling "Abrau-Durso" 2022',
                'description_ru'   => 'Россия, Краснодарский край. Белое сухое. Цветочные ароматы, свежая кислотность, минеральный финиш. Отличный аперитив',
                'description_en'   => 'Russia, Krasnodar region. Dry white. Floral aromas, fresh acidity, mineral finish. Excellent aperitif',
                'price'            => 2900,
                'featured'         => false,
                'sort_order'       => 4,
            ],

            // ── Напитки ───────────────────────────────────────────────────
            [
                'menu_category_id' => $cats['drinks'],
                'title_ru'         => 'Авторский лимонад «Белая ночь»',
                'title_en'         => '"White Night" Signature Lemonade',
                'description_ru'   => 'Огурец, мята, лемонграсс, elderflower, тоник. Безалкогольный. 500 мл',
                'description_en'   => 'Cucumber, mint, lemongrass, elderflower, tonic. Non-alcoholic. 500 ml',
                'price'            => 490,
                'featured'         => false,
                'sort_order'       => 1,
            ],
            [
                'menu_category_id' => $cats['drinks'],
                'title_ru'         => 'Чай из иван-чая с мёдом',
                'title_en'         => 'Fireweed Tea with Honey',
                'description_ru'   => 'Ферментированный иван-чай из Алтая, мёд алтайской пасеки, чабрец. Чайник 500 мл',
                'description_en'   => 'Fermented fireweed tea from Altai, Altai honey, thyme. Teapot 500 ml',
                'price'            => 380,
                'featured'         => false,
                'sort_order'       => 2,
            ],
        ];

        foreach ($items as $item) {
            MenuItem::create($item);
        }
    }
}
